Update testing page: fix the pytest command
As I understand correctly the pytest command does not support anymore the option --asyncio-mode=strict.
So I suggest to remove it in the documentation.

Also if I run the command with the option I get an error:
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --asyncio-mode=strict
  inifile: /workspaces/core/pyproject.toml
  rootdir: /workspaces/core